spring:
  datasource:
    url: jdbc:mysql://localhost:3306/esa_db?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate: 
      ddl-auto: update
    show-sql: true
    properties: 
      hibernate:
        format_sql: true
        
  #SMTP Configuration
  mail: 
    host: smtp.gmail.com
    port: 587
    username: ${mail.username}
    password: ${mail.password}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
    
    